name: GENERATE ASCII Artwork

on: push
# on: [push, fork]

jobs:
    build_job_one:
        runs-on: ubuntu-latest
        steps: 
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: EXECUTE COWSAY CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        - name: Sleep for thirty seconds
          run: sleep 30

    test_job_two:
        needs: build_job_one
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10

        - name: test file exists
          run: grep -i "dragon" dragon.txt

    deploy_job_three:
        needs: test_job_two
        runs-on: ubuntu-latest
        steps:

        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploy. .. .....  ... 

