name: GENERATE ASCII Artwork

on: push
# on: [push, fork]

jobs:
    build_job_one:
        runs-on: ubuntu-latest
        steps: 
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: EXECUTE COWSAY CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        - name: Upload Dragon Text File
          uses: actions/upload-artifact@v3
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job_two:
        needs: build_job_one
        runs-on: ubuntu-latest
        steps:
        - name: Upload Dragon Text File
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file

        - name: test file exists
          run: grep -i "dragon" dragon.txt

    deploy_job_three:
        needs: test_job_two
        runs-on: ubuntu-latest
        steps:
        - name: Upload Dragon Text File
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file

        - name: Read file
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploy. .. .....  ... 

